version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - ollama